/*what is the total revenue generated by male and female customers?*/
select gender, SUM(purchase_amount) as revenue from customer group by gender;

/*which customers used a discount but still spent more than the average purchase amount?*/
select customer_id,purchase_amount 
from customer
where discount_applied='Yes' and purchase_amount>=(select AVG(purchase_amount) from customer) ;

/*which are the top 5 products with the highest average review rating?*/
SELECT item_purchased,
       ROUND(AVG(CAST(review_rating AS DECIMAL(3,2))), 2) AS Average_Product_Rating
FROM customer
GROUP BY item_purchased
ORDER BY Average_Product_Rating DESC
LIMIT 5;

/*Compare the average purchase amount between standard and express shipping*/
select shipping_type,
AVG(purchase_amount)
from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type;

/*Do subscribed customers spend more ?Comapre average spend and total revenue between subscribers and non-subscribers*/
select subscription_status,
COUNT(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(SUM(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue,avg_spend desc;

/*which 5 products have the highest percentage of purchase with discounts applied?*/
SELECT item_purchased,
       ROUND(
           SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) 
           * 100.0 / COUNT(*),
           2
       ) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

/*segment customers into new, returning,and Loyal based on their total number of purchases and how the count of each segment*/
WITH customer_type AS (
    SELECT 
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
)
SELECT 
    customer_segment,
    COUNT(*) AS Number_of_Customers
FROM customer_type
GROUP BY customer_segment;

/*what are the top 3 most purchased products within each category?*/
WITH item_counts AS (
SELECT  category,
item_purchased,
COUNT(customer_id) AS total_orders

    FROM customer
    GROUP BY category, item_purchased
),
ranked_items AS (
    SELECT
        category,
        item_purchased,
        total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY total_orders DESC
        ) AS item_rank
    FROM item_counts
)
SELECT item_rank, category, item_purchased, total_orders
FROM ranked_items;

/*Are the customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe*/
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases>5
group by subscription_status;  
/*what is the revenue contribution of each age group*/
select age_group,
sum(purchase_amount) as total_revenue
from customer 
group by age_group
order by total_revenue desc;
